---
- name: Install everything
  hosts: localhost
  connection: local
  remote_user: root

  tasks:
    - name: Update pacman
      community.general.pacman:
        update_cache: yes
        upgrade: yes

    - name: Install 'yay'
      community.general.pacman:
        name: yay
        state: present
        
    - name: Install vscode
      community.general.pacman:
        name: code
        state: present
        executable: yay
        extra_args: --builddir /var/cache/yay


